### PR TITLE
Added unshared objects

### PR DESCRIPTION
**Pull request by snovichkov**
Hi, I added non shared objects like a same feature in [Symfony DI](https://symfony.com/doc/current/service_container/shared.html). Please review my merge request and merge them if everything is fine. Thx.

### CODE REVIEW

**Comment by sarulabs** [comment]
Hello,

I am not a big fan of the `unshared` feature, but it does not have any impact on the default behaviour. So I don't mind adding it.

But the problem is more complex than it appears, because your code does not handle the `Close` function. Even if the objects are not shared, you still need to store them in the container so that they can be closed when the container is deleted.

In your test, you need to add a Close function and ensure that this function is called for each created object.

In the code, I think the best way to handle this would be to add a field `unsharedObjects` to `containerCore`. This field would be a `map[string][]interface{}`.

Some things that need to be done:

- check where `containerCore` are instantiated to initialize the new map
- update the `containerGetter` to create the objects and store them in the new map
- update the `containerSlayer` to close the objects

These should be enough but I would not guarantee it.

In the `containerGetter` you do not need to have channels to ensure that only one unshared object is created at a time. The best way to update the code would probably to have:

```go
func (g *containerGetter) getInThisContainer(ctn *container, def Def) (interface{}, error) {
    if def.Unshared {
        return g.getUnsharedObjectInThisContainer(ctn, def)
    }
    return g.getSharedObjectInThisContainer(ctn, def)
}
```

This way you could have your own method and you would not complexify the current code.

Also I am a little worried about the dependency graph. With unshared objects, you can write:

```go
Def{
    Name: "object",
    Build: func(ctn Container) (interface{}, error) {
        if time.Now().Unix() % 2 == 0 {
            return ctn.Get("depA"), nil
        }
        return ctn.Get("depB"), nil
    },
    Unshared: true,
}
```

Before writing code, we need to evaluate the impacts of this kind of things to `containerCore.dependencies` and `container.builtList`.

**Comment by snovichkov** [comment]
@sarulabs Hello, thanks for the explanation. Looks like I fixed all comments . Please review again.

**Comment by snovichkov** [comment]
Hello, I have idea about the problem with impact unshared objects to `containerCore.dependencies`, `container.builtList` that you are describing above and it seems to me that I have found a solution to the problem. It is worth changing the concept that you described above to a concept with uniqueness of names for each unshared object, this completely solves this problem. @sarulabs What you think about this solution?

**Comment by sarulabs** [comment]
Hello, I think this is promising and you are going in the right direction. But it is still flawed.

Changing the name of the definition breaks the `builtList`. With this you can have an unshared object that depends on itself. That makes things more complicated.

Also I don't like the `UnsharedSeparator`. It is a bit hacky and probably breaks if someone want to use it in a definition name.

I will try to take some time this weekend to think about this more in details.

**Comment by sarulabs** [comment]
I thought about this and I think I came up with a decent solution:

Storing the unshared objects in a different map was not a very good idea. It makes things more complicated.

To store the unshared objects in the objects map I propose to create a new type for the key:

```go
// could be added at the top of the utils.go file
type objectKey struct {
	defName string
	uniqueID int
}

type containerCore struct {
	// ...
	lastUniqueID int
	objects map[objectKey]interface{}
	// ...
}
```

This way there is nearly nothing to do in the slayer. And in the getter it is not complicated either:

```go
func (g *containerGetter) getInThisContainer(ctn *container, def Def) (interface{}, error) {
	ctn.m.Lock()

	if ctn.closed {
		ctn.m.Unlock()
		return nil, fmt.Errorf("could not get `%s` because the container has been deleted", def.Name)
	}

	objKey objectKey{defName: def.Name}
	if def.Unshared {
 		ctn.lastUniqueID += 1
		objKey.uniqueID = ctn.lastUniqueID
	}

	// ...
}
```

Some method need to be updated to handle the `objectKey`:

```go
func (g *containerGetter) addDependencyToGraph(ctn *container, objKey objectKey) {}
func (g *containerGetter) buildInThisContainer(ctn *container, def Def, objKey objectKey, c buildingChan) (interface{}, error) {}
func (g *containerGetter) build(ctn *container, def Def, objKey objectKey) (obj interface{}, err error) {}
```

The `builtList` and `graph` also need to be updated. For the `graph` it is easy, but for the `builtList` the expected behaviour is not exactly the same.

I think the structure could be:

```go
type builtList struct {
	last objectKey
	elements map[string]int
}
```

The `last` field is used to update the graph, so it needs to be an `objectKey`. But the `elements` field is used to avoid cycles. So the definition name is what we need.

What do you think about this solution ? I am not 100% it works but it seems fine and have a minimal impact on the current code.

**Comment by snovichkov** [comment]
@sarulabs Hi, your solution looks good, but for me this is a more complicated solution. However, I implemented what you described earlier. Could you review code again?

**Comment by sarulabs** [comment]
This solution may seem more complicated because I introduced the `objectKey`. But using a `string` with a special separator was not a viable solution in my opinion.

Sorry but there is still an error in the `builtList`. I think the type should be:
```go
type builtList struct {
	last objectKey
	elements map[string]int
}
```
with:
```go
func (l builtList) Has(name string) bool {} // could be renamed HasDef but it is not important
func (l builtList) OrderedList() []string
```
For unshared objects, you don't want to check if there is `objectKey{defName: def.Name}` in the built list, because it is not. You only want to check if one object with the same definition has been built.

**Comment by sarulabs** [comment]
I merged your code.
Thank you for your contribution.

**Pull request merged**
